[package]
name = "racing-space"
version = "0.1.0"
authors.workspace = true
description.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
bevy = { version = "0.16.1", features = ["web"] }
bevy_web_asset = "0.11.0"
tracing.workspace = true