[package]
name = "telegram-bot"
version = "0.1.0"
authors.workspace = true
description.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
teloxide = "0.16.0"
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
