[package]
name = "ratel-mcp-server"
version = "0.1.0"
authors.workspace = true
description.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
anyhow = "1.0.98"
axum = { version = "0.8.4", features = ["macros"] }
rmcp = { version = "0.1.5", git = "https://github.com/modelcontextprotocol/rust-sdk", features = ["server", "transport-io", "transport-streamable-http-server", "transport-sse-server"] }
serde.workspace = true
serde_json.workspace = true
tokio = { version = "1.45.1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = [
    "env-filter",
    "std",
    "fmt",
] }